# ============================================
# SERVICE MANIFEST
# A Service provides network access to Pods
# ============================================

apiVersion: v1
kind: Service

# --------------------------------------------
# SERVICE METADATA
# Information about the Service itself
# --------------------------------------------
metadata:
  name: frontend-service          # Name of this Service

# --------------------------------------------
# SERVICE SPECIFICATION
# Defines how the Service routes traffic
# --------------------------------------------
spec:
  type: NodePort                  # Expose on each Node's IP at a static port
                                  # Other types: ClusterIP, LoadBalancer

  # ==========================================
  # SELECTOR - How Service finds Pods
  # ==========================================
  # This tells the Service: "Route traffic to all Pods with label app=frontend"
  # Must match the label defined in Deployment's Pod template!
  selector:
    app: frontend                 # Find Pods with this label

  # ==========================================
  # PORTS - Network port mapping
  # ==========================================
  ports:
    - port: 3000                  # Service port (used inside cluster)
      targetPort: 3000            # Container port (where app listens)
      nodePort: 30000             # External port (access from outside: localhost:30000)

# ============================================
# HOW IT WORKS:
# 
# External Request (localhost:30000)
#         |
#         v
#    [NodePort: 30000]
#         |
#         v
#    [Service Port: 3000]
#         |
#         v
#    [selector: app=frontend] --> Finds all Pods with label "app: frontend"
#         |
#    +---------+---------+
#    |                   |
#    v                   v
#  Pod 1               Pod 2
#  (targetPort:3000)   (targetPort:3000)
# ============================================
