apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    app: frontend
spec:
  containers:
    - name: frontend
      image: k8s-demo-frontend:v1
      imagePullPolicy: Never
      ports:
        - containerPort: 3000
