apiVersion: v1
kind: Pod
metadata:
  name: backend-pod
  labels:
    app: backend
spec:
  containers:
    - name: backend
      image: k8s-demo-backend:1.0
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 3000
      env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
