apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    {{- include "k8s-demo.labels" (merge (dict "component" "frontend") .) | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 80
      {{- if eq .Values.frontend.service.type "NodePort" }}
      nodePort: {{ .Values.frontend.service.nodePort }}
      {{- end }}
