apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    app: frontend
spec:
  containers:
    - name: frontend
      image: k8s-demo-frontend:1.0
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
